### ISSUE TITLE
load() never completes

### ISSUE THREAD

**Issue by macismail2003** [NativeScript/template-master-detail#71]
Hi,
Thank you for the awesome project. It is quite useful. I followed what was instructed and in minutes time, I was able to install the app with my own firebase setup. But later, I faced one small issue which doesn't seem to get solved. Please help! I was able to read data from my Firebase from the load() and the data was rendered on to the app nicely. But after some time, even though I can read data from Firebase, the load() function never goes to either finally() or subscribe(). What could be the reason?

cars-list-view-model.ts
-----------------------

load(): void {
        this.isLoading = true;
        console.log("Before loading...");
        this._carService.load()
            .finally(() => {
                console.log("done2");
                this.isLoading = false
            })
            .subscribe(
                (cars: Array<Car>) => {
                console.log("done1");
                this.cars = new ObservableArray(cars);
                this.isLoading = false;
                },
                (error) => {
                    console.log(error);
                });
    }

car-service.ts
--------------

    load(): Observable<any> {
        return new Observable((observer: any) => {
            const path = "Cars";
            console.log("Path Set");
            const onValueEvent = (snapshot: any) => {
                const results = this.handleSnapshot(snapshot.value);
                //console.log(snapshot.values);
                for (let key in snapshot.value) {
                    console.log(key);
                }
            };
            firebase.addValueEventListener(onValueEvent, `/${path}`);
            console.log("After event listener");
        }).catch(this.handleErrors);
    }

Since it doesn't go to finally or subscribe, the loading indicator never goes off. Please help. Thank you.
Seyed Ismail.

**Comment by MartoYankov** [comment]
Hi @macismail2003 

Can you please elaborate more on what you mean by "after some time"? Are you talking about one run of the app - it works on first load, but fails on consecutive loads? Or is it the case that your app simply stopped working? Also, how did you establish that you are getting the data from Firebase?

**Comment by manoldonev** [comment]
@macismail2003 unfortunately so far we are unable to reproduce the described behavior in our local tests. Do you experience the same behavior on multiple app runs on your end? Can you provide a step by step guide how to reproduce this so we can investigate further?
